version: '3'
services:
  web:
    container_name: psums_aggregator
    build: .
    restart: always
    ports:
      - '80:80'
    links:
      - db
      - memcached
    volumes:
      - .:/var/www/html
  db:
    container_name: psums_mysql
    image: mysql
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
  memcached:
    container_name: psums_memcached
    image: memcached
    ports:
      - '11211:11211'
